# Generated by Django 4.2.2 on 2023-06-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
