# Generated by Django 4.2.2 on 2023-06-21 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_likes_post_user_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
